### ISSUE TITLE
GSS is Pivotal Support

### ISSUE THREAD

**Issue by joefitzgerald** [pivotal-cf/glossary#42]
GSS (Global Support Services) is an old name previously used to refer to the team that is now known as `Pivotal Support`. They have been trying **mightily** to leave the GSS moniker in the dust, and it just won't die. Let's help them out and update this entry!

https://github.com/pivotal-cf/glossary/blob/58946d7e082a8281c7d825df12d39678a4042d54/entries/GSS.yml#L3

/cc @pivotal-cf/support

**Comment by jhamon** [comment]
I think the entry description would be a good place to add information about the history of the term. I don't think deleting the current definition is a good approach, though, since people still do encounter GSS and might wonder what that means. Thoughts? @joefitzgerald

**Comment by pivotal-manuel-morales** [comment]
I was just reviewing this repo and saw this issue. IMO, we should obsolete GSS from all Pivotal docs and use something like Pivotal Support (formally known as GSS). If GSS is mentioned anywhere else it should be replaced by "Pivotal Support". Since there is no acronym, can it just be deleted and also removed from the references to it from the Geo's. In other places just do find/replace to use our official name "Pivotal Support"
